int _putchar(char c);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int wrapper(int n, int guess);
int is_prime_number(int n);
int divide_number(int n, int guess);
int _strlen_recursion(char *s);
int count_letters(int i, char *s);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
